### ISSUE TITLE
robot crypto omg example does not work as shown in your example

### ISSUE THREAD

**Issue by snazzybunny** [jonmcoe/hubot-crypto#1]
Hello, thanks for this hubot script. I am having trouble with the command "hubot crypto omg". It says that it cannot find OMG in terms of BTC but in your example it shows that it works. Here is some more info:

Part of the log:
at Feb 03 2018 21:39:16 GMT-0500 (EST)] INFO Message receive callback id LEdvXDDQPq4HsooAa ts Sat Feb 03 2018 21:39:16 GMT-0500 (EST)
[Sat Feb 03 2018 21:39:16 GMT-0500 (EST)] INFO [Incoming] snazzybunny: hubot crypto omg
[Sat Feb 03 2018 21:39:16 GMT-0500 (EST)] INFO setting roomName: general
[Sat Feb 03 2018 21:39:16 GMT-0500 (EST)] INFO Message sent to hubot brain.
[Sat Feb 03 2018 21:39:17 GMT-0500 (EST)] INFO Sending Message To Room: general
[Sat Feb 03 2018 21:39:17 GMT-0500 (EST)] INFO Message received with ID id

In chat:
snazzybunny Admin 9:39 PM
hubot crypto omg

hubot 9:39 PM
Could not find OMG in terms of BTC

**Comment by jonmcoe** [comment]
Thanks for reporting this @snazzybunny . It appears that the source API has moved OMG, and any other ethereum derived tokens, to a different index called `tokens`. See https://apiv2.bitcoinaverage.com/#supported-currencies.

So what we used to get at
https://apiv2.bitcoinaverage.com/indices/crypto/ticker/OMGBTC

We will now get from
https://apiv2.bitcoinaverage.com/indices/tokens/ticker/OMGBTC

In https://github.com/jonmcoe/hubot-crypto/commit/f28af2ffaf8bde318104e0f0a8311b1f015b4a46 we begin looking in the correct location, so it should work exactly as described in the README once again. Can you upgrade to `0.5.0`, give it a try, and confirm that it's working for you?

**Comment by snazzybunny** [comment]
Just upgraded to 0.5.0. Seems to be working fine now, thanks! Is it possible to check if a coin such as btc hits a limit and then announces it to the channel?

**Comment by jonmcoe** [comment]
Glad it's working for you!

Price alerts like that would require a pretty big change from / addition to how it works now. It definitely sounds cool ("Bitcoin is over 10,000 USD!"), but unfortunately I do not think this is a feature that will be added any time soon.

Nonetheless, feel free to write separate issue or open a PR for it.
